spring:
  application:
    name: spring-ai-tutorials
  ai:
    openai:
      base-url: ${OPENAI_API_BASE}
      api-key: ${MY_API_KEY}
      chat:
        options:
          model: gpt-4o
    qianfan:
      api-key: ${QIAN_FAN_API_KEY}
      secret-key: ${QIAN_FAN_SECRET}
    zhipuai:
      api-key: ${ZHI_PU_API_KEY}

