spring:
  application:
    name: aiDocs
  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: rookie
    password: rookie123456
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://ai-yyds.com
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only

